name: Purge jsDelivr (manual)

on:
  workflow_dispatch:   # enables the "Run workflow" button in Actions

jobs:
  purge:
    runs-on: ubuntu-latest
    steps:
      - name: Purge jsDelivr cache
        uses: gacts/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/T3s0/Testing-1@main/index.html
            https://cdn.jsdelivr.net/gh/T3s0/Testing-1@main/style.css
            https://cdn.jsdelivr.net/gh/T3s0/Testing-1@main/script.js
